// Centralized mock movie data for the entire application

import { TrendingUp, Star, Calendar, Zap, Target, Compass, Film } from "lucide-react"

export const movieCategories = {
  trending: [
    {
      id: 1,
      title: "Oppenheimer",
      year: "2023",
      rating: 8.4,
      genre: ["Biography", "Drama", "History"],
      poster: "/placeholder.svg?height=450&width=300&text=Oppenheimer",
      description:
        "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    },
    {
      id: 2,
      title: "Barbie",
      year: "2023",
      rating: 7.0,
      genre: ["Adventure", "Comedy", "Fantasy"],
      poster: "/placeholder.svg?height=450&width=300&text=Barbie",
      description:
        "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.",
    },
    {
      id: 3,
      title: "Spider-Man: Across the Spider-Verse",
      year: "2023",
      rating: 8.7,
      genre: ["Animation", "Action", "Adventure"],
      poster: "/placeholder.svg?height=450&width=300&text=Spider-Verse",
      description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People.",
    },
    {
      id: 4,
      title: "John Wick: Chapter 4",
      year: "2023",
      rating: 7.7,
      genre: ["Action", "Crime", "Thriller"],
      poster: "/placeholder.svg?height=450&width=300&text=John+Wick+4",
      description: "John Wick uncovers a path to defeating The High Table.",
    },
    {
      id: 5,
      title: "Guardians of the Galaxy Vol. 3",
      year: "2023",
      rating: 7.9,
      genre: ["Action", "Adventure", "Comedy"],
      poster: "/placeholder.svg?height=450&width=300&text=Guardians+3",
      description: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe.",
    },
    {
      id: 6,
      title: "Fast X",
      year: "2023",
      rating: 5.8,
      genre: ["Action", "Adventure", "Crime"],
      poster: "/placeholder.svg?height=450&width=300&text=Fast+X",
      description: "Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.",
    },
  ],
  popular: [
    {
      id: 7,
      title: "The Shawshank Redemption",
      year: "1994",
      rating: 9.3,
      genre: ["Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=Shawshank+Redemption",
      description: "Two imprisoned men bond over years, finding solace and redemption through acts of common decency.",
    },
    {
      id: 8,
      title: "The Godfather",
      year: "1972",
      rating: 9.2,
      genre: ["Crime", "Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=The+Godfather",
      description: "The aging patriarch of a crime dynasty transfers control to his son.",
    },
    {
      id: 9,
      title: "The Dark Knight",
      year: "2008",
      rating: 9.0,
      genre: ["Action", "Crime", "Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=The+Dark+Knight",
      description: "Batman faces the Joker in this epic crime saga.",
    },
    {
      id: 10,
      title: "Pulp Fiction",
      year: "1994",
      rating: 8.9,
      genre: ["Crime", "Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=Pulp+Fiction",
      description: "The lives of two mob hitmen intertwine in this crime classic.",
    },
    {
      id: 11,
      title: "Forrest Gump",
      year: "1994",
      rating: 8.8,
      genre: ["Drama", "Romance"],
      poster: "/placeholder.svg?height=450&width=300&text=Forrest+Gump",
      description: "The presidencies of Kennedy and Johnson through the eyes of an Alabama man.",
    },
    {
      id: 12,
      title: "Inception",
      year: "2010",
      rating: 8.8,
      genre: ["Sci-Fi", "Thriller", "Action"],
      poster: "/placeholder.svg?height=450&width=300&text=Inception",
      description: "A thief who steals corporate secrets through dream-sharing technology.",
    },
  ],
  action: [
    {
      id: 13,
      title: "Mad Max: Fury Road",
      year: "2015",
      rating: 8.1,
      genre: ["Action", "Adventure", "Sci-Fi"],
      poster: "/placeholder.svg?height=450&width=300&text=Mad+Max",
      description: "In a post-apocalyptic wasteland, Max teams up with Furiosa to flee from a cult leader.",
    },
    {
      id: 14,
      title: "Die Hard",
      year: "1988",
      rating: 8.2,
      genre: ["Action", "Thriller"],
      poster: "/placeholder.svg?height=450&width=300&text=Die+Hard",
      description: "A New York police officer tries to save his wife and several others taken hostage.",
    },
    {
      id: 15,
      title: "Terminator 2: Judgment Day",
      year: "1991",
      rating: 8.6,
      genre: ["Action", "Sci-Fi"],
      poster: "/placeholder.svg?height=450&width=300&text=Terminator+2",
      description: "A cyborg is sent back in time to protect John Connor from a more advanced Terminator.",
    },
    {
      id: 16,
      title: "The Matrix",
      year: "1999",
      rating: 8.7,
      genre: ["Action", "Sci-Fi"],
      poster: "/placeholder.svg?height=450&width=300&text=The+Matrix",
      description: "A computer hacker learns about the true nature of reality.",
    },
    {
      id: 17,
      title: "Heat",
      year: "1995",
      rating: 8.3,
      genre: ["Action", "Crime", "Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=Heat",
      description: "A group of professional bank robbers start to feel the heat from police.",
    },
    {
      id: 18,
      title: "Mission: Impossible",
      year: "1996",
      rating: 7.2,
      genre: ["Action", "Adventure", "Thriller"],
      poster: "/placeholder.svg?height=450&width=300&text=Mission+Impossible",
      description: "An American agent, under false suspicion of disloyalty, must discover the real spy.",
    },
  ],
  scifi: [
    {
      id: 19,
      title: "Blade Runner 2049",
      year: "2017",
      rating: 8.0,
      genre: ["Action", "Drama", "Mystery"],
      poster: "/placeholder.svg?height=450&width=300&text=Blade+Runner+2049",
      description: "A young blade runner discovers a secret that could plunge what's left of society into chaos.",
    },
    {
      id: 20,
      title: "Interstellar",
      year: "2014",
      rating: 8.6,
      genre: ["Adventure", "Drama", "Sci-Fi"],
      poster: "/placeholder.svg?height=450&width=300&text=Interstellar",
      description: "A team of explorers travel through a wormhole in space.",
    },
    {
      id: 21,
      title: "Arrival",
      year: "2016",
      rating: 7.9,
      genre: ["Drama", "Mystery", "Sci-Fi"],
      poster: "/placeholder.svg?height=450&width=300&text=Arrival",
      description: "A linguist works with the military to communicate with alien lifeforms.",
    },
    {
      id: 22,
      title: "Ex Machina",
      year: "2014",
      rating: 7.7,
      genre: ["Drama", "Sci-Fi", "Thriller"],
      poster: "/placeholder.svg?height=450&width=300&text=Ex+Machina",
      description:
        "A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence.",
    },
    {
      id: 23,
      title: "Dune",
      year: "2021",
      rating: 8.0,
      genre: ["Action", "Adventure", "Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=Dune",
      description: "Paul Atreides leads nomadic tribes in a revolt against the galactic emperor.",
    },
    {
      id: 24,
      title: "Star Wars: A New Hope",
      year: "1977",
      rating: 8.6,
      genre: ["Action", "Adventure", "Fantasy"],
      poster: "/placeholder.svg?height=450&width=300&text=Star+Wars",
      description: "Luke Skywalker joins forces with a Jedi Knight to save Princess Leia.",
    },
  ],
  drama: [
    {
      id: 25,
      title: "The Godfather Part II",
      year: "1974",
      rating: 9.0,
      genre: ["Crime", "Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=Godfather+2",
      description: "The early life of Vito Corleone in 1920s New York City is portrayed.",
    },
    {
      id: 26,
      title: "12 Angry Men",
      year: "1957",
      rating: 9.0,
      genre: ["Crime", "Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=12+Angry+Men",
      description: "A jury holdout attempts to prevent a miscarriage of justice.",
    },
    {
      id: 27,
      title: "Schindler's List",
      year: "1993",
      rating: 9.0,
      genre: ["Biography", "Drama", "History"],
      poster: "/placeholder.svg?height=450&width=300&text=Schindlers+List",
      description: "In German-occupied Poland, industrialist Oskar Schindler saves his Jewish employees.",
    },
    {
      id: 28,
      title: "One Flew Over the Cuckoo's Nest",
      year: "1975",
      rating: 8.7,
      genre: ["Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=Cuckoos+Nest",
      description: "A criminal pleads insanity and is admitted to a mental institution.",
    },
    {
      id: 29,
      title: "Goodfellas",
      year: "1990",
      rating: 8.7,
      genre: ["Biography", "Crime", "Drama"],
      poster: "/placeholder.svg?height=450&width=300&text=Goodfellas",
      description: "The story of Henry Hill and his life in the mob.",
    },
    {
      id: 30,
      title: "The Pianist",
      year: "2002",
      rating: 8.5,
      genre: ["Biography", "Drama", "Music"],
      poster: "/placeholder.svg?height=450&width=300&text=The+Pianist",
      description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto.",
    },
  ],
}

export const discoverMovies = [
  {
    id: 31,
    title: "Avatar: The Way of Water",
    year: "2022",
    rating: 7.6,
    genre: ["Action", "Adventure", "Drama"],
    poster: "/placeholder.svg?height=450&width=300&text=Avatar+2",
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora.",
  },
  {
    id: 32,
    title: "Top Gun: Maverick",
    year: "2022",
    rating: 8.3,
    genre: ["Action", "Drama"],
    poster: "/placeholder.svg?height=450&width=300&text=Top+Gun+Maverick",
    description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator.",
  },
  {
    id: 33,
    title: "Everything Everywhere All at Once",
    year: "2022",
    rating: 7.8,
    genre: ["Action", "Adventure", "Comedy"],
    poster: "/placeholder.svg?height=450&width=300&text=Everything+Everywhere",
    description: "A middle-aged Chinese immigrant is swept up into an insane adventure.",
  },
  {
    id: 34,
    title: "The Batman",
    year: "2022",
    rating: 7.8,
    genre: ["Action", "Crime", "Drama"],
    poster: "/placeholder.svg?height=450&width=300&text=The+Batman",
    description:
      "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
  },
  {
    id: 35,
    title: "Dune: Part Two",
    year: "2024",
    rating: 8.5,
    genre: ["Action", "Adventure", "Drama"],
    poster: "/placeholder.svg?height=450&width=300&text=Dune+2",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators.",
  },
  {
    id: 36,
    title: "No Time to Die",
    year: "2021",
    rating: 7.3,
    genre: ["Action", "Adventure", "Thriller"],
    poster: "/placeholder.svg?height=450&width=300&text=No+Time+to+Die",
    description: "James Bond has left active service when his friend Felix Leiter enlists his help.",
  },
]

export const allMovies = [
  ...Object.values(movieCategories).flat(),
  ...discoverMovies,
  {
    id: 1,
    title: "Oppenheimer",
    year: "2023",
    rating: 8.4,
    genre: ["Biography", "Drama", "History"],
    poster: "/placeholder.svg?height=450&width=300&text=Oppenheimer",
    backdrop: "/placeholder.svg?height=800&width=1200&text=Oppenheimer+Backdrop",
    description:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    runtime: "180 min",
    releaseDate: "July 21, 2023",
    budget: "$100 million",
    boxOffice: "$952.8 million",
    plot: "During World War II, Lt. Gen. Leslie Groves Jr. appoints physicist J. Robert Oppenheimer to work on the top-secret Manhattan Project. Oppenheimer and a team of scientists spend years developing and designing the atomic bomb. Their work comes to fruition on July 16, 1945, as they witness the world's first nuclear explosion, forever changing the course of history.",
  },
  {
    id: 7,
    title: "The Shawshank Redemption",
    year: "1994",
    rating: 9.3,
    genre: ["Drama"],
    poster: "/placeholder.svg?height=450&width=300&text=Shawshank+Redemption",
    backdrop: "/placeholder.svg?height=800&width=1200&text=Shawshank+Backdrop",
    description: "Two imprisoned men bond over years, finding solace and redemption through acts of common decency.",
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    runtime: "142 min",
    releaseDate: "September 23, 1994",
    budget: "$25 million",
    boxOffice: "$16.3 million",
    plot: "Andy Dufresne, a successful banker, is arrested for the murders of his wife and her lover, and is sentenced to life imprisonment at the Shawshank State Penitentiary. He becomes the most unconventional prisoner.",
  },
  {
    id: 16,
    title: "The Matrix",
    year: "1999",
    rating: 8.7,
    genre: ["Action", "Sci-Fi"],
    poster: "/placeholder.svg?height=450&width=300&text=The+Matrix",
    description: "A computer hacker learns about the true nature of reality.",
  },
  {
    id: 20,
    title: "Interstellar",
    year: "2014",
    rating: 8.6,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    poster: "/placeholder.svg?height=450&width=300&text=Interstellar",
    description: "A team of explorers travel through a wormhole in space.",
  },
  {
    id: 9,
    title: "The Dark Knight",
    year: "2008",
    rating: 9.0,
    genre: ["Action", "Crime", "Drama"],
    poster: "/placeholder.svg?height=450&width=300&text=The+Dark+Knight",
    description: "Batman faces the Joker in this epic crime saga.",
  },
]

export const featuredMovie = {
  id: 1,
  title: "Oppenheimer",
  year: "2023",
  rating: 8.4,
  genre: ["Biography", "Drama", "History"],
  backdrop: "/placeholder.svg?height=800&width=1400&text=Oppenheimer+Hero+Backdrop",
  description:
    "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
  director: "Christopher Nolan",
  cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
}

export const quickFilters = [
  {
    label: "Trending Now",
    icon: TrendingUp,
    filter: { genres: [], yearRange: [2020, 2024] },
    description: "What's hot right now",
  },
  {
    label: "Highly Rated",
    icon: Star,
    filter: { genres: [], ratingRange: [8.5, 10] },
    description: "Critics' favorites",
  },
  {
    label: "Recent Releases",
    icon: Calendar,
    filter: { genres: [], yearRange: [2022, 2024] },
    description: "Fresh from theaters",
  },
  {
    label: "Action Packed",
    icon: Zap,
    filter: { genres: ["Action"] },
    description: "High-octane thrills",
  },
  {
    label: "Sci-Fi Wonders",
    icon: Target,
    filter: { genres: ["Sci-Fi"] },
    description: "Future fantasies",
  },
  {
    label: "Drama Classics",
    icon: Compass,
    filter: { genres: ["Drama"] },
    description: "Emotional journeys",
  },
]

export const quickStats = [
  { label: "Total Movies", value: "30+", icon: Film },
  { label: "Genres", value: "15+", icon: Star },
  { label: "Years Covered", value: "50+", icon: Calendar },
  { label: "Trending Now", value: "6", icon: TrendingUp },
]

export const similarMovies = [
  {
    id: 16,
    title: "The Matrix",
    year: "1999",
    rating: 8.7,
    genre: ["Action", "Sci-Fi"],
    poster: "/placeholder.svg?height=450&width=300&text=The+Matrix",
    description: "A computer hacker learns about the true nature of reality.",
  },
  {
    id: 20,
    title: "Interstellar",
    year: "2014",
    rating: 8.6,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    poster: "/placeholder.svg?height=450&width=300&text=Interstellar",
    description: "A team of explorers travel through a wormhole in space.",
  },
  {
    id: 9,
    title: "The Dark Knight",
    year: "2008",
    rating: 9.0,
    genre: ["Action", "Crime", "Drama"],
    poster: "/placeholder.svg?height=450&width=300&text=The+Dark+Knight",
    description: "Batman faces the Joker in this epic crime saga.",
  },
]
